### ISSUE TITLE
A footer is Required.

### ISSUE THREAD

**Issue by bilalshaikh292** [hackbysarthak03/Hacktoberfest2023#16]

**Comment by slaughterhectic** [comment]
please assign it to me I can do it

**Comment by hackbysarthak03** [comment]
@slaughterhectic please proceed. I have assigned it to you.

**Comment by MasterIfeanyi** [comment]
@hackbysarthak03 please assign this to me.

**Comment by slaughterhectic** [comment]
@hackbysarthak03 footer updated
