### ISSUE TITLE
Update the Footer

### ISSUE THREAD

**Issue by hackbysarthak03** [hackbysarthak03/Hacktoberfest2023#26]
Make it look simple and interactive

**Comment by Devesh1509** [comment]
hey @hackbysarthak03  i'd like to work on this issue under hacktoberfest 2023.
assign me

**Comment by Ammu003** [comment]
@hackbysarthak03 can you please assign this issue to me . i would like to work on it

**Comment by VishnuAmit** [comment]
@hackbysarthak03 I am doing it. Please assign it to me. I am from telegram group :)

**Comment by AdityaKumar2408** [comment]
Can you assign this task to me. If you have any doubts, you can check my other repos for that.

**Comment by harshitadubey1203** [comment]
Shall I proceed with this @hackbysarthak03
