### ISSUE TITLE
Work on the contact form.

### ISSUE THREAD

**Issue by HummadP** [hackbysarthak03/Hacktoberfest2023#73]
hey @hackbysarthak03 , I would like to work on the contact form styling. pls assign me so that I can start working on it.

**Comment by RahulSoni2532** [comment]
I am so excited to work on this issue please  assign  me @hackbysarthak03

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign me this issue.

**Comment by Kedarnath-Rothe** [comment]
I am very exited to solve this issue .... Please assign this issue to me....
